package models;
// Generated 14/mai/2023 14:11:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento  implements java.io.Serializable {


     private Integer idPag;
     private Viatura viatura;
     private Date dataPag;
     private String nrDocCliente;
     private String nomeCliente;
     private int diasParq;

    public Pagamento() {
    }

    public Pagamento(Viatura viatura, Date dataPag, String nrDocCliente, String nomeCliente, int diasParq) {
       this.viatura = viatura;
       this.dataPag = dataPag;
       this.nrDocCliente = nrDocCliente;
       this.nomeCliente = nomeCliente;
       this.diasParq = diasParq;
    }
   
    public Integer getIdPag() {
        return this.idPag;
    }
    
    public void setIdPag(Integer idPag) {
        this.idPag = idPag;
    }
    public Viatura getViatura() {
        return this.viatura;
    }
    
    public void setViatura(Viatura viatura) {
        this.viatura = viatura;
    }
    public Date getDataPag() {
        return this.dataPag;
    }
    
    public void setDataPag(Date dataPag) {
        this.dataPag = dataPag;
    }
    public String getNrDocCliente() {
        return this.nrDocCliente;
    }
    
    public void setNrDocCliente(String nrDocCliente) {
        this.nrDocCliente = nrDocCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public int getDiasParq() {
        return this.diasParq;
    }
    
    public void setDiasParq(int diasParq) {
        this.diasParq = diasParq;
    }




}


