package models;
// Generated 14/mai/2023 14:11:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viatura generated by hbm2java
 */
public class Viatura  implements java.io.Serializable {


     private String matricula;
     private Cliente cliente;
     private int marca;
     private int modelo;
     private int cor;
     private String status;
     private Date dataRegisto;
     private Set pagamentos = new HashSet(0);

    public Viatura() {
    }

	
    public Viatura(String matricula, Cliente cliente, int marca, int modelo, int cor, String status, Date dataRegisto) {
        this.matricula = matricula;
        this.cliente = cliente;
        this.marca = marca;
        this.modelo = modelo;
        this.cor = cor;
        this.status = status;
        this.dataRegisto = dataRegisto;
    }
    public Viatura(String matricula, Cliente cliente, int marca, int modelo, int cor, String status, Date dataRegisto, Set pagamentos) {
       this.matricula = matricula;
       this.cliente = cliente;
       this.marca = marca;
       this.modelo = modelo;
       this.cor = cor;
       this.status = status;
       this.dataRegisto = dataRegisto;
       this.pagamentos = pagamentos;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getMarca() {
        return this.marca;
    }
    
    public void setMarca(int marca) {
        this.marca = marca;
    }
    public int getModelo() {
        return this.modelo;
    }
    
    public void setModelo(int modelo) {
        this.modelo = modelo;
    }
    public int getCor() {
        return this.cor;
    }
    
    public void setCor(int cor) {
        this.cor = cor;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDataRegisto() {
        return this.dataRegisto;
    }
    
    public void setDataRegisto(Date dataRegisto) {
        this.dataRegisto = dataRegisto;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }




}


